import = [
    "~/.config/alacritty/themes/themes/terminal_app.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
startup_mode = "Maximized"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 14

